### ISSUE TITLE
Exception When Setting PageHeader In SendFax

### ISSUE THREAD

**Issue by evanjpw** [interfax/interfax-java#19]
When sending a fax with ``sendFax`` providing ``SendFaxOptions``, if I set the page header to the example found in [the documentation](https://www.interfax.net/en/dev/rest/reference/2918) thusly:

```Java

		options.setPageHeader(Optional.ofNullable("To: {To} From: {From} Pages: {TotalPages}"));

```

I get the following exception:

```

java.lang.illegalargumentexception: The template variable 'To' has no value
        at org.glassfish.jersey.uri.UriTemplate$1ValuesFromArrayStrategy.valueFor(UriTemplate.java:1020) ~[jersey-common-2.23.2.jar:?]
        at org.glassfish.jersey.uri.UriTemplate.resolveTemplate(UriTemplate.java:706) ~[jersey-common-2.23.2.jar:?]
at org.glassfish.jersey.uri.UriTemplate.createUriComponent(UriTemplate.java:1030) ~[jersey-common-2.23.2.jar:?]
        at org.glassfish.jersey.uri.UriTemplate.createURIWithStringValues(UriTemplate.java:970) ~[jersey-common-2.23.2.jar:?]
        at org.glassfish.jersey.uri.UriTemplate.createURIWithStringValues(UriTemplate.java:906) ~[jersey-common-2.23.2.jar:?]
        at org.glassfish.jersey.uri.UriTemplate.createURI(UriTemplate.java:871) ~[jersey-common-2.23.2.jar:?]
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder._build(JerseyUriBuilder.java:914) ~[jersey-common-2.23.2.jar:?]
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder.build(JerseyUriBuilder.java:831) ~[jersey-common-2.23.2.jar:?]
        at net.interfax.rest.client.impl.DefaultInterFAXClient.getSendFaxUri(DefaultInterFAXClient.java:705) ~[api-client-0.6.jar:?]
        at net.interfax.rest.client.impl.DefaultInterFAXClient.sendMultiPartFax(DefaultInterFAXClient.java:585) ~[api-client-0.6.jar:?]
	at net.interfax.rest.client.impl.DefaultInterFAXClient.sendFax(DefaultInterFAXClient.java:170) ~[api-client-0.6.jar:?]

```

I don't have time to debug this at the moment but I thought that it was important to document it.

**Comment by evanjpw** [comment]
A bit of searching found 
[Jersey client crashes on curly brackets](https://java.net/jira/browse/JERSEY-3075)

and
[Incoming URL components are parsed for bracket paths](https://java.net/jira/si/jira.issueviews:issue-html/JERSEY-2525/JERSEY-2525.html)

**Comment by anuragkapur** [comment]
Thanks for reporting this. I'll investigate.

**Comment by anuragkapur** [comment]
Ok, so I can reproduce this. A workaround is to encode the pageheader string before passing it.

Example:
```java
String pageHeader = "To: {To} From: {From} Pages: {TotalPages}";
sendFaxOptions.setPageHeader(Optional.of(URLEncoder.encode(pageHeader, StandardCharsets.UTF_8.toString())));
```

I am going to investigate further into the Jersey bug report you referenced above to come up with a robust fix for this.

**Comment by evanjpw** [comment]
Awesome! That will work nicely. Thank you so much!

**Comment by anuragkapur** [comment]
FYI - version 0.8.0 onwards handles encoding the `pageHeader` implicitly and the client of the library does not have to (and should not) encode pageHeader before using the API method(s).
